redhawk/accounts/urls.py
from django.conf.urls import url
from . import views

# We are adding a URL called /home
urlpatterns = [
    url(r'^$', views.index, name='index'),
    
    # url(r'^category/(?P<category_name_url>\w+)$', views.category, name='category'),
    # url(r'^add_category/$', views.add_category, name='add_category'),
    # url(r'^category/(?P<category_name_url>\w+)/add_page/$', views.add_page, name='add_page'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.logout, name='logout'),
]

redhawk/redhawk/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


import cimpress_redhawk, accounts





urlpatterns = [
    url(r'^admin/', admin.site.urls),

    # url(r'^', include('users.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^cimpress_redhawk/', include('cimpress_redhawk.urls')),


]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

redhawk/accounts/models.py
from django.contrib.auth.models import User
from django.db import models

class UserProfile(models.Model):
    # This line is required. Links UserProfile to a User model instance.
    user = models.OneToOneField(User)

    # The additional attributes we wish to include.
    address1 = models.CharField(blank=True, max_length = 200)
    address2 = models.CharField(blank=True, max_length = 200)

    # Override the __unicode__() method to return out something meaningful!
    def __unicode__(self):
        return self.user.username

redhawk/accounts/forms.py
from .models import UserProfile
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('address1', 'address2')

redhawk/accounts/views.py
from .forms import UserForm, UserProfileForm
from django.shortcuts import render_to_response
from django.shortcuts import render
from django.template import RequestContext
from django.views.decorators import csrf
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib import auth

def index(request):
	return render(request, 'index.html')

def register(request):
    # Like before, get the request's context.
    context = RequestContext(request)

    # A boolean value for telling the template whether the registration was successful.
    # Set to False initially. Code changes value to True when registration succeeds.
    registered = False

    # If it's a HTTP POST, we're interested in processing form data.
    if request.method == 'POST':
        # Attempt to grab information from the raw form information.
        # Note that we make use of both UserForm and UserProfileForm.
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        # If the two forms are valid...
        if user_form.is_valid() and profile_form.is_valid():
            # Save the user's form data to the database.
            user = user_form.save()

            # Now we hash the password with the set_password method.
            # Once hashed, we can update the user object.
            user.set_password(user.password)
            user.save()
            print user

            # Now sort out the UserProfile instance.
            # Since we need to set the user attribute ourselves, we set commit=False.
            # This delays saving the model until we're ready to avoid integrity problems.
            profile = profile_form.save(commit=False)
            profile.user = user

            # Did the user provide a profile picture?
            # If so, we need to get it from the input form and put it in the UserProfile model.
            # if 'picture' in request.FILES:
            #     profile.picture = request.FILES['picture']

            # Now we save the UserProfile model instance.
            profile.save()

            # Update our variable to tell the template registration was successful.
            registered = True

        # Invalid form or forms - mistakes or something else?
        # Print problems to the terminal.
        # They'll also be shown to the user.
        else:
            print user_form.errors, profile_form.errors

    # Not a HTTP POST, so we render our form using two ModelForm instances.
    # These forms will be blank, ready for user input.
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    # Render the template depending on the context.
    return render(request,
            'register.html',
            {'user_form': user_form, 'profile_form': profile_form, 'registered': registered},
            )

def user_login(request):
    # Like before, obtain the context for the user's request.
    context = RequestContext(request)

    # If the request is a HTTP POST, try to pull out the relevant information.
    if request.method == 'POST':
        # Gather the username and password provided by the user.
        # This information is obtained from the login form.

        username = request.POST.get('username')
        password = request.POST.get('password')


        # Use Django's machinery to attempt to see if the username/password
        # combination is valid - a User object is returned if it is.
        user = authenticate(username=username, password=password)

        # If we have a User object, the details are correct.
        # If None (Python's way of representing the absence of a value), no user
        # with matching credentials was found.
        if user:
            # Is the account active? It could have been disabled.
            if user.is_active:
                # If the account is valid and active, we can log the user in.
                # We'll send the user back to the homepage.
                login(request, user)
                return HttpResponseRedirect("http://127.0.0.1:8000/cimpress_redhawk/")
            else:
                # An inactive account was used - no logging in!
                return HttpResponse("Your account is disabled.")
        else:
            # Bad login details were provided. So we can't log the user in.
            print "Invalid login details: {0}, {1}".format(username, password)
            return HttpResponse("Invalid Credentials")


    # The request is not a HTTP POST, so display the login form.
    # This scenario would most likely be a HTTP GET.
    else:
        # No context variables to pass to the template system, hence the
        # blank dictionary object...
        return render(request,'login.html', {}, context)

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/accounts/login')

redhawk/accounts/templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Vista Bot</title>

	<link rel="stylesheet" type="text/css" href='{% static "bootstrap/css/bootstrap.min.css" %}'>
</head>
<body>
	<div class='fluid-container'>
		<nav class="navbar navbar-inverse" style="border-radius: 0;">
		  <div class="container-fluid">    
		    <div class="navbar-header">
		      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#NavbarCollapse" aria-expanded="false">
		        <span class="sr-only">Toggle navigation</span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		        <span class="icon-bar"></span>
		      </button>
		      <a class="navbar-brand" href="#"><p style="font-size:30px;font-weight: bold;">Vista Bot</p></a>
		    </div>

		    <div class="collapse navbar-collapse" id="NavbarCollapse">

		      <ul class="nav navbar-nav navbar-right">
		        {% if not request.user.is_authenticated %}
		        <li class='pull-right'><a href='{% url "register" %}'><p style="font-size:22px;font-weight: bold;">Register</p></a></li>
		        <li class='pull-right'><a href='{% url "login" %}'><p style="font-size:22px;font-weight: bold;">Login</p></a></li>
		        {% else %}
		        <li class='pull-right'><p style="font-size:22px;">Hi, {{ user.username }}!</p></li>
		        <li class='pull-right'><a href='{% url "logout" %}'><p style="font-size:22px;font-weight: bold;">Logout</p></a></li>
		        {% endif %}
		      </ul>
		    </div>
		  </div>
		</nav>
	</div>
<script src='{% static "bootstrap/js/bootstrap.min.js" %}'></script>

</body>
</html>

redhawk/accounts/templates/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Vista Bot</title>

    <link rel="stylesheet" type="text/css" href='{% static "bootstrap/css/bootstrap.min.css" %}'>
</head>
<body>
    <div class='fluid-container'>
        <nav class="navbar navbar-inverse" style="border-radius: 0;">
          <div class="container-fluid">    
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#NavbarCollapse" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#"><p style="font-size:30px;font-weight: bold;">Vista Bot</p></a>
            </div>

            <div class="collapse navbar-collapse" id="NavbarCollapse">

              <ul class="nav navbar-nav navbar-right">
                {% if not request.user.is_authenticated %}
                <li class='pull-right'><a href='{% url "register" %}'><p style="font-size:22px;font-weight: bold;">Register</p></a></li>
                <li class='pull-right'><a href='{% url "login" %}'><p style="font-size:22px;font-weight: bold;">Login</p></a></li>
                {% else %}
                <li class='pull-right'><a href='{% url "logout" %}'><p style="font-size:22px;font-weight: bold;">Logout</p></a></li>
                {% endif %}
              </ul>
            </div>
          </div>
        </nav>
    </div>

        <div class="container">
            <form id="login_form" method="post" action="/accounts/login/" class="form-horizontal" role="form">
                {% csrf_token %}
                <h1><center>Enter your credentials</center></h1><br><br>
                <div class="form-group">
                    <label for="id_username" class="col-sm-4 control-label">Username</label>
                    <div class="col-sm-6">
                        <input type="text" id="username" name="username" placeholder="Username" class="form-control" autofocus>
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-sm-4 control-label">Password</label>
                    <div class="col-sm-6">
                        <input type="password" id="password" name="password" placeholder="Password" class="form-control">
                    </div>
                </div>
                <br>
                <div class="form-group">
                    <div class="col-sm-2 col-sm-offset-4">
                        <button type="submit" value="submit" class="btn btn-success btn-block">Login</button>
                    </div>
                </div>
            </form>
        </div>


<script src='{% static "bootstrap/js/bootstrap.min.js" %}'></script>
</body>

</html>

redhawk/accounts/templates/register.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Vista Bot</title>

    <link rel="stylesheet" type="text/css" href='{% static "bootstrap/css/bootstrap.min.css" %}'>
</head>
<body>
    <div class='fluid-container'>
        <nav class="navbar navbar-inverse" style="border-radius: 0;">
          <div class="container-fluid">    
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#NavbarCollapse" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="#"><p style="font-size:30px;font-weight: bold;">Vista Bot</p></a>
            </div>

            <div class="collapse navbar-collapse" id="NavbarCollapse">

              <ul class="nav navbar-nav navbar-right">
                {% if not request.user.is_authenticated %}
                <li class='pull-right'><a href='{% url "register" %}'><p style="font-size:22px;font-weight: bold;">Register</p></a></li>
                <li class='pull-right'><a href='{% url "login" %}'><p style="font-size:22px;font-weight: bold;">Login</p></a></li>
                {% else %}
                <li class='pull-right'><p style="font-size:22px;">Hi, {{ user.username }}!</p></li>
                <li class='pull-right'><a href='{% url "logout" %}'><p style="font-size:22px;font-weight: bold;">Logout</p></a></li>
                {% endif %}
              </ul>
            </div>
          </div>
        </nav>
    </div>

        <div class="container">
            <form id="login_form" method="post" action="/accounts/register/" class="form-horizontal" role="form">
                {% csrf_token %}
                <h1><center>Registration Form</center></h1><br><br>
                <div class="form-group">
                    <label for="id_username" class="col-sm-4 control-label">Username</label>
                    <div class="col-sm-6">
                        <input type="text" id="id_username" name="username" placeholder="Username" class="form-control" autofocus>
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_email" class="col-sm-4 control-label">Email</label>
                    <div class="col-sm-6">
                        <input type="email" id="id_email" name="email" placeholder="Email" class="form-control">
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-sm-4 control-label">Password</label>
                    <div class="col-sm-6">
                        <input type="password" id="id_password" name="password" placeholder="Password" class="form-control">
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_address1" class="col-sm-4 control-label">Address Line 1</label>
                    <div class="col-sm-6">
                        <input type="text" id="id_address1" name="address1" placeholder="Address Line 1" class="form-control" autofocus>
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_address2" class="col-sm-4 control-label">Address Line 2</label>
                    <div class="col-sm-6">
                        <input type="text" id="id_address2" name="address2" placeholder="Address Line 2" class="form-control" autofocus>
                    </div>
                </div>
                <br>
                <div class="form-group">
                    <div class="col-sm-2 col-sm-offset-4">
                        <button type="submit" name="submit" value="Register" class="btn btn-success btn-block">Register</button>
                    </div>
                </div>
            </form>
        </div>


<script src='{% static "bootstrap/js/bootstrap.min.js" %}'></script>
</body>

</html>